
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university-data
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run seed && npm start"

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: